create table public.hostels (
  id bigint generated by default as identity primary key,
  name text not null,
  area text not null,
  address text not null,
  gender text not null check (gender in ('Boys','Girls')),
  monthly_rent integer not null,
  distance_km numeric(5,2),
  description text,
  phone text,
  image_url text,
  verified boolean default false,
  created_at timestamptz default now()
);

create table public.hostel_reviews (
  id bigint generated by default as identity primary key,
  hostel_id bigint references public.hostels(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  university text,
  review_text text not null,
  cleanliness numeric(2,1) check (cleanliness between 1 and 5),
  food numeric(2,1) check (food between 1 and 5),
  wifi numeric(2,1) check (wifi between 1 and 5),
  owner_behaviour numeric(2,1) check (owner_behaviour between 1 and 5),
  verified_student boolean default false,
  created_at timestamptz default now()
);

create table public.owner_listings (
  id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete cascade,
  hostel_name text not null,
  owner_name text not null,
  whatsapp text not null,
  hostel_type text not null,
  monthly_rent integer not null,
  address text not null,
  description text,
  status text default 'pending',
  created_at timestamptz default now()
);

alter table public.hostels enable row level security;
alter table public.hostel_reviews enable row level security;
alter table public.owner_listings enable row level security;

create policy "Anyone can view hostels"
on public.hostels for select using (true);

create policy "Anyone can view approved reviews"
on public.hostel_reviews for select using (verified_student = true);

create policy "Logged-in users can submit reviews"
on public.hostel_reviews for insert to authenticated
with check (auth.uid() = user_id);

create policy "Owners can submit listings"
on public.owner_listings for insert to authenticated
with check (auth.uid() = owner_id);

create policy "Owners can view their listings"
on public.owner_listings for select to authenticated
using (auth.uid() = owner_id);
